var src = 'src';
var dist = 'dist';
module.exports={
    html:{
        src:src+'/**/*.{html,htm}',
        dest:dist+'/',
    },
    sass:{
        src:src+'/scss/**/*.scss',
        destsrc:src+'/css',
        dest:dist+'/css',
        main:src+'/scss/main.scss'
    },
    less:{
        src:src+'/less/**/main.less',
        dest:dist+'/css',
        destsrc:src+'/css',
    },
    img:{
        src:src+'/img/**/*.{jpg,ico}',
        dest:dist+'/img'
    },
    css:{
        src:src+'/css/**/*.css',
        dest:dist+'/css'
    },
    js:{
        src:src+'/js/**/*.js',
        dest:dist+'/js',
    }
};
